version: '3.5'

services:
  api1: # API - Instância 01
    # image: api
    build: .
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    restart: on-failure
    environment:
      DATABASE_URL: "postgresql://rinha:rinhabackend@db:5432/rinha-backend?schema=public"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    # image: api
    build: .
    hostname: api2
    depends_on:
      - db
    expose:
      - "80"
    restart: on-failure
    environment:
      DATABASE_URL: "postgresql://rinha:rinhabackend@db:5432/rinha-backend?schema=public"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    environment:
      POSTGRES_PASSWORD: rinhabackend
      POSTGRES_USER: rinha
      POSTGRES_DB: rinha-backend
    ports:
      - 5432:5432
    expose:
      - "5432"

networks:
  default:
    driver: bridge